version: "3.8"

services:
  doctor-api:
    links: 
      - doctor-mysql
    container_name: doctor-API
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    image: testback:lastest
    working_dir: /usr/src/app
    ports:
      - "3000:8080"
    environment:
      DB_HOST: doctor-mysql
      DB_PORT: 3306
      DB_USERNAME: "admin"
      DB_PASSWORD: "admin"
      DB_DATABASE: "Heal"
    networks:
      - testnet
  doctor-mysql:
    container_name: doctor-mysql2
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "Heal"
    ports: 
      - "3306:3306"
    networks:
      - testnet
networks:
  testnet:
    driver: bridge