FROM node:buster

WORKDIR /usr/src/app

COPY package*.json ./

COPY . .

RUN npm install -g @nestjs/cli

RUN npm install --only=production

RUN npm run build

EXPOSE 8080

CMD [ "npm", "run", "start:dev" ]